//! The native views an app has registered, and what the compiler needs to know
//! about them (RFC-0039 §"Compiler & dev-loop").
//!
//! # Why this is a process-wide registry
//!
//! The set of element names a program understands is fixed before the first
//! `.byd` file is read: an app builds its views, hands them to the engine, and
//! from then on `c.Sparkline(...)` either resolves or is a compile error with a
//! span. That is the same lifetime the intrinsic table has, which is why a
//! registered view lands in the *same* catalog an intrinsic is looked up in
//! rather than in a parallel one the checker has to remember to consult.
//!
//! Registration is therefore startup-only and append-only, and the entries are
//! leaked deliberately: a native view outlives every frame that uses it, so
//! reference counting its metadata would be paying for a lifetime nobody ends.
//!
//! # What crosses to the compiler, and what does not
//!
//! Plain data: a name, prop names with their types and whether each reaches
//! layout, event names. No `byard-core` type appears in a `byard-compiler`
//! signature because of this, and no compiler type appears here (INV-1). The
//! factory stays on this side, because making a view is making engine state.

use std::sync::RwLock;

use super::view::NativeView;

/// The type of one declared prop, in the vocabulary the language already has.
///
/// Deliberately the small closed set, not "any Rust type": a prop is written in
/// `byld`, so it can only ever be something `byld` can express, and a view that
/// wants a structure takes a record or a list of them.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum NativePropType {
    /// A whole number, in logical pixels or as a count.
    Int,
    /// A fractional number.
    Float,
    /// A boolean.
    Bool,
    /// A string.
    Str,
    /// A hex colour.
    Color,
    /// A `(Float, Float)` pair.
    Vec2,
    /// A list of numbers, the shape a chart's data takes.
    Floats,
}

/// One prop a native view declares.
#[derive(Clone, Copy, Debug)]
pub struct NativeProp {
    /// The name it is written under in `byld`.
    pub name: &'static str,
    /// The value type it accepts.
    pub ty: NativePropType,
    /// Whether changing it can move geometry (RFC-0032 §R2's `AttrClass`).
    ///
    /// A native view answers this per prop for the same reason an intrinsic
    /// does: the invalidation model needs to know whether a change can only
    /// repaint or must also relayout, and a prop with no answer is one the
    /// engine has to assume the worst about.
    pub layout: bool,
}

/// Everything the compiler needs to treat a native view as an element.
#[derive(Clone, Copy, Debug)]
pub struct NativeViewInfo {
    /// The element name written in `byld`.
    pub name: &'static str,
    /// The props it accepts.
    pub props: &'static [NativeProp],
    /// The events it can raise, on top of the pointer events every element
    /// already has.
    pub events: &'static [&'static str],
}

/// A native view that can be registered: it knows its own catalog entry and
/// how to make one of itself.
///
/// Generated by `#[byard::native_view]`, which is why it is two items rather
/// than a `Default` bound: a view's initial state is not always its type's
/// default, and the macro knows which.
pub trait NativeViewMeta: NativeView {
    /// This view's catalog entry.
    const INFO: NativeViewInfo;

    /// Makes a fresh instance, called once per element that declares it.
    fn create() -> Box<dyn NativeView>;
}

/// One registered view: its catalog entry and the factory that makes one.
struct Entry {
    info: NativeViewInfo,
    factory: fn() -> Box<dyn NativeView>,
}

/// The registered views, in registration order.
static REGISTRY: RwLock<Vec<Entry>> = RwLock::new(Vec::new());

/// Registers `V` so `byld` can name it (RFC-0039).
///
/// Registering the same name twice replaces nothing and adds nothing: the
/// first registration wins and this returns `false`, because an app that
/// registers two different views under one name has an ambiguity the engine
/// cannot resolve for it, and silently picking one would make which widget
/// appears depend on link order.
pub fn register<V: NativeViewMeta>() -> bool {
    let Ok(mut registry) = REGISTRY.write() else {
        return false;
    };
    if registry.iter().any(|e| e.info.name == V::INFO.name) {
        return false;
    }
    registry.push(Entry {
        info: V::INFO,
        factory: V::create,
    });
    true
}

/// The catalog entry registered under `name`, if any.
#[must_use]
pub fn info(name: &str) -> Option<NativeViewInfo> {
    let registry = REGISTRY.read().ok()?;
    registry
        .iter()
        .find(|e| e.info.name == name)
        .map(|e| e.info)
}

/// Every registered view's name, in registration order.
#[must_use]
pub fn names() -> Vec<&'static str> {
    REGISTRY
        .read()
        .map(|r| r.iter().map(|e| e.info.name).collect())
        .unwrap_or_default()
}

/// Makes an instance of the view registered under `name`.
///
/// Returns `None` for a name nobody registered, which the caller turns into a
/// diagnostic; there is no fallback view, because an element that silently
/// renders nothing is the failure mode RFC-0039 exists to avoid (INV-4).
#[must_use]
pub fn create(name: &str) -> Option<Box<dyn NativeView>> {
    let registry = REGISTRY.read().ok()?;
    let factory = registry.iter().find(|e| e.info.name == name)?.factory;
    let mut view = factory();
    view.on_mount();
    Some(view)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::{Layout, NativeProps, RenderCtx};

    struct Probe;

    impl NativeProps for Probe {}

    impl NativeView for Probe {
        fn render(&mut self, _layout: Layout, _cx: &mut RenderCtx<'_>) {}
    }

    impl NativeViewMeta for Probe {
        const INFO: NativeViewInfo = NativeViewInfo {
            name: "RegistryProbe",
            props: &[NativeProp {
                name: "data",
                ty: NativePropType::Floats,
                layout: false,
            }],
            events: &["hover_point"],
        };
        fn create() -> Box<dyn NativeView> {
            Box::new(Self)
        }
    }

    struct Impostor;

    impl NativeProps for Impostor {}

    impl NativeView for Impostor {
        fn render(&mut self, _layout: Layout, _cx: &mut RenderCtx<'_>) {}
    }

    impl NativeViewMeta for Impostor {
        const INFO: NativeViewInfo = NativeViewInfo {
            name: "RegistryProbe",
            props: &[],
            events: &[],
        };
        fn create() -> Box<dyn NativeView> {
            Box::new(Self)
        }
    }

    #[test]
    fn a_registered_view_is_findable_by_name_and_instantiable() {
        // Not `assert!(register(...))`: the sibling test registers the same
        // name, and which of the two runs first is the test harness's
        // business. What both tests assert is the property, not the order.
        register::<Probe>();
        let info = info("RegistryProbe").expect("registered");
        assert_eq!(info.props[0].name, "data");
        assert_eq!(info.events, &["hover_point"]);
        assert!(create("RegistryProbe").is_some());
        assert!(
            create("NoSuchView").is_none(),
            "an unregistered name has no fallback view"
        );
    }

    #[test]
    fn a_second_view_cannot_take_a_name_that_is_taken() {
        // Order-dependent-but-not-really: whichever of these two tests runs
        // first registers the name, and the other's `register` is the one that
        // must be refused. Both outcomes are asserted through the same
        // property, so this does not depend on test order.
        let first = register::<Probe>();
        let second = register::<Impostor>();
        assert!(
            !(first && second),
            "two views cannot share a name; the second registration is refused"
        );
        assert!(names().contains(&"RegistryProbe"));
    }
}
