//! Procedural macros for byard (M23 — controller boundary).
//!
//! `#[byard_controller]` marks a Rust struct as a byard controller: it can
//! provide ambient values via `inject`, expose async methods, and deliver
//! results back to the logic thread through the relay's I/O channel.
//!
//! The macro emits the struct **unchanged** and adds an inherent `impl` exposing
//! field metadata the interpreter needs for type-directed member-access (M5:
//! `member → field type`). The generated code is self-contained — it introduces
//! **no dependency on `byard-core`/`byard-compiler`**, so those crates never gain
//! a runtime back-dependency on `byard-macro` (INV-1). The metadata is consumed
//! by the application crate that owns the controller.

use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, Type, parse_macro_input};

/// Marks a Rust struct as a byard controller.
///
/// The struct is emitted unchanged, plus an inherent `impl` with:
///
/// - `pub const BYARD_FIELDS: &[(&str, &str)]` — `(field name, byld type name)`
///   for every named field, in declaration order;
/// - `pub fn byard_field_type(name: &str) -> Option<&'static str>` — the byld
///   type of one field, for the interpreter's `member → field type` inference.
///
/// Rust scalar types map to byld scalars (`i*`/`u* → Int`, `f* → Float`,
/// `bool → Bool`, `String`/`&str → Str`); any other type maps to its final path
/// segment (so a nested controller type keeps its name).
///
/// # Example
///
/// ```ignore
/// #[byard_controller]
/// struct CounterController {
///     count: i64,
///     label: String,
/// }
/// assert_eq!(CounterController::byard_field_type("count"), Some("Int"));
/// ```
#[proc_macro_attribute]
pub fn byard_controller(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as DeriveInput);
    let name = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    // Collect (field name, byld type) for each named field. Non-struct or
    // tuple/unit structs simply produce empty metadata (still valid).
    let mut entries = Vec::new();
    if let Data::Struct(s) = &input.data
        && let Fields::Named(named) = &s.fields
    {
        for field in &named.named {
            if let Some(ident) = &field.ident {
                let fname = ident.to_string();
                let bty = byld_type_name(&field.ty);
                entries.push((fname, bty));
            }
        }
    }

    let field_names: Vec<&str> = entries.iter().map(|(n, _)| n.as_str()).collect();
    let field_types: Vec<&str> = entries.iter().map(|(_, t)| t.as_str()).collect();

    let expanded = quote! {
        #input

        impl #impl_generics #name #ty_generics #where_clause {
            /// `(field name, byld type)` metadata for every named field, in
            /// declaration order. Consumed by the byard interpreter for
            /// type-directed `member` access (generated by `#[byard_controller]`).
            pub const BYARD_FIELDS: &'static [(&'static str, &'static str)] = &[
                #( ( #field_names, #field_types ) ),*
            ];

            /// The byld type name of one field, or `None` if no such field
            /// exists (generated by `#[byard_controller]`).
            #[must_use]
            pub fn byard_field_type(name: &str) -> ::core::option::Option<&'static str> {
                Self::BYARD_FIELDS
                    .iter()
                    .find(|(n, _)| *n == name)
                    .map(|(_, t)| *t)
            }
        }
    };

    TokenStream::from(expanded)
}

/// Maps a Rust field type to the byld type name the interpreter understands.
fn byld_type_name(ty: &Type) -> String {
    let ident = match ty {
        Type::Path(p) => p.path.segments.last().map(|s| s.ident.to_string()),
        Type::Reference(r) => return byld_type_name(&r.elem),
        _ => None,
    };
    match ident.as_deref() {
        Some(
            "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "u8" | "u16" | "u32" | "u64" | "u128"
            | "usize",
        ) => "Int".to_string(),
        Some("f32" | "f64") => "Float".to_string(),
        Some("bool") => "Bool".to_string(),
        Some("String" | "str") => "Str".to_string(),
        Some(other) => other.to_string(),
        None => "Unknown".to_string(),
    }
}
