//! `byard build [file]` — the AOT vector-atlas bake (RFC-0009 §4, M49).
//!
//! Resolves the whole module graph, statically closes the set of icons the app
//! instantiates (tree-shaking dormant assets, guarding non-literal handles),
//! generates + dedups + MaxRects-packs them into one immutable atlas, and emits
//! a coordinate table plus the packed texels under `.byard/generated/`.
//!
//! The table is written as a standalone `vector_atlas.rs` (a `[BakedGlyph; N]`)
//! rather than inlined into a transpiled binary — the Prod transpiler
//! (RFC-0001 §7.3) does not exist yet, so this is the forward-compatible
//! artifact it will `include!` once it lands. Everything up to that final
//! hand-off — analysis, guard, generation, packing, emission — is done here.

use std::fmt::Write as _;
use std::path::Path;

use byard_compiler::vector::{BakedVectorAtlas, bake_atlas, collect_static_vector_refs};

use crate::deps::resolve_project;
use crate::manifest::Manifest;

pub fn run(file: Option<&Path>) -> Result<(), String> {
    let manifest = Manifest::discover(file)?;
    println!("  Byard 0.0.0 — build (AOT vector atlas)");
    println!("  Entry: {}", manifest.entry.display());

    let (program, _provider) = resolve_project(&manifest)?;
    if !program.errors.is_empty() {
        for err in &program.errors {
            eprintln!("{}", program.source_map.render_line(err));
        }
        return Err(format!(
            "{} error(s) — fix them before building",
            program.errors.len()
        ));
    }

    // Stage 1: close the icon set (tree-shake) with the RFC-0009 §4 guard.
    let (refs, errors) = collect_static_vector_refs(&program.views, &manifest.vector_includes);
    if !errors.is_empty() {
        for err in &errors {
            eprintln!("{}", program.source_map.render_line(err));
        }
        return Err(format!(
            "{} vector asset error(s) — a partial atlas is never shipped",
            errors.len()
        ));
    }

    // Stages 2–3: generate + dedup + pack.
    let baked = bake_atlas(&refs, &manifest.project_root).map_err(|errs| {
        for err in &errs {
            eprintln!("{}", program.source_map.render_line(err));
        }
        format!("{} vector bake error(s)", errs.len())
    })?;

    let out_dir = manifest.project_root.join(".byard").join("generated");
    std::fs::create_dir_all(&out_dir).map_err(|e| format!("{}: {e}", out_dir.display()))?;
    let bin = out_dir.join("vector_atlas.bin");
    let table = out_dir.join("vector_atlas.rs");
    std::fs::write(&bin, &baked.atlas).map_err(|e| format!("{}: {e}", bin.display()))?;
    std::fs::write(&table, emit_table(&baked)).map_err(|e| format!("{}: {e}", table.display()))?;

    println!(
        "  Baked {} icon(s) into {} layer(s) of {}² — {}",
        baked.table.len(),
        baked.layers,
        baked.size,
        out_dir.display()
    );
    Ok(())
}

/// Emits the coordinate table as a standalone, `@generated` Rust source file:
/// a `[BakedGlyph; N]` the runtime (or the future transpiler) indexes with no
/// parsing or coordinate math. `f32` values use their shortest round-tripping
/// decimal form (`{:?}`), so the emitted UVs are byte-exact.
fn emit_table(baked: &BakedVectorAtlas) -> String {
    let mut s = String::new();
    s.push_str(
        "// @generated by `byard build` — RFC-0009 §4 AOT vector atlas. Do not edit.\n\
         //\n\
         // Pairs with `vector_atlas.bin`: RGBA8 texels, `size*size*layers*4` bytes,\n\
         // layer-major then row-major (top row first).\n\n\
         /// One baked MSDF glyph's coordinate-table entry.\n\
         pub struct BakedGlyph {\n\
         \x20   /// Source asset handle (the runtime lookup key).\n\
         \x20   pub handle: &'static str,\n\
         \x20   /// Normalized UV corners `(u0, v0, u1, v1)` within the atlas.\n\
         \x20   pub uv_rect: [f32; 4],\n\
         \x20   /// Array-texture layer.\n\
         \x20   pub layer: u32,\n\
         \x20   /// Baked distance range (RFC-0009 §2-E).\n\
         \x20   pub px_range: f32,\n\
         }\n\n",
    );
    let _ = writeln!(s, "pub const VECTOR_ATLAS_SIZE: u32 = {};", baked.size);
    let _ = writeln!(s, "pub const VECTOR_ATLAS_LAYERS: u32 = {};", baked.layers);
    let _ = writeln!(
        s,
        "pub static VECTOR_ATLAS: [BakedGlyph; {}] = [",
        baked.table.len()
    );
    for g in &baked.table {
        let _ = writeln!(
            s,
            "    BakedGlyph {{ handle: {:?}, uv_rect: [{:?}, {:?}, {:?}, {:?}], layer: {}, px_range: {:?} }},",
            g.handle, g.uv_rect[0], g.uv_rect[1], g.uv_rect[2], g.uv_rect[3], g.layer, g.px_range
        );
    }
    s.push_str("];\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    const SQUARE: &str = r##"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <path d="M4 4 L20 4 L20 20 L4 20 Z" fill="#000000"/></svg>"##;

    #[test]
    fn build_bakes_the_atlas_artifact_for_a_project() {
        let dir = std::env::temp_dir().join(format!("byard_build_it_{}", std::process::id()));
        let src = dir.join("src");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::write(
            dir.join("byard.toml"),
            "[project]\nname = \"t\"\nentry = \"src/main.byd\"\n",
        )
        .unwrap();
        std::fs::write(
            src.join("main.byd"),
            "View Main() { VectorIcon(\"src/icon.svg\") #[size: 24] }",
        )
        .unwrap();
        std::fs::write(src.join("icon.svg"), SQUARE).unwrap();

        run(Some(&dir)).expect("build must succeed on a well-formed project");

        let table = std::fs::read_to_string(dir.join(".byard/generated/vector_atlas.rs")).unwrap();
        assert!(
            table.contains("VECTOR_ATLAS: [BakedGlyph; 1]"),
            "one icon must be baked:\n{table}"
        );
        assert!(
            table.contains("src/icon.svg"),
            "the handle must be in the table"
        );
        assert!(
            dir.join(".byard/generated/vector_atlas.bin").exists(),
            "the packed texels must be written"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn build_fails_on_a_dynamic_asset_without_an_include_list() {
        let dir = std::env::temp_dir().join(format!("byard_build_dyn_{}", std::process::id()));
        let src = dir.join("src");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::write(
            dir.join("byard.toml"),
            "[project]\nname = \"t\"\nentry = \"src/main.byd\"\n",
        )
        .unwrap();
        std::fs::write(
            src.join("main.byd"),
            "View Main() { var p = \"src/icon.svg\" VectorIcon(p) #[size: 24] }",
        )
        .unwrap();

        let err = run(Some(&dir)).expect_err("a dynamic asset must fail the build");
        assert!(err.contains("vector asset error"), "{err}");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
