[package]
name = "controller-demo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
byard = { path = "../../crates/byard" }
tokio = { version = "1", features = ["time"] }

[lints]
workspace = true
