//! Lexer for the Byard template language.
//!
//! Generates tokens from the source string using the `logos` crate.

use logos::{Lexer, Logos};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum ScanState {
    InString,
    InBraceExpr,
}

/// Callback manual to scan interpolated string literals with nested expressions.
fn scan_interpolated_string(lex: &mut Lexer<Token>) -> bool {
    let mut state_stack = [ScanState::InString; 8];
    let mut stack_ptr = 1;

    let start_pos = lex.span().end;
    let source = lex.source();
    let chars = source[start_pos..].chars();
    let mut bytes_read = 0;
    let mut is_escaped = false;

    for c in chars {
        bytes_read += c.len_utf8();

        if is_escaped {
            is_escaped = false;
            continue;
        }

        if c == '\\' {
            is_escaped = true;
            continue;
        }

        let current_state = state_stack[stack_ptr - 1];

        match current_state {
            ScanState::InString => {
                if c == '"' {
                    stack_ptr -= 1;
                    if stack_ptr == 0 {
                        lex.bump(bytes_read);
                        return true;
                    }
                } else if c == '{' {
                    if stack_ptr < 8 {
                        state_stack[stack_ptr] = ScanState::InBraceExpr;
                        stack_ptr += 1;
                    } else {
                        return false;
                    }
                }
            }
            ScanState::InBraceExpr => {
                if c == '}' {
                    stack_ptr -= 1;
                } else if c == '"' {
                    if stack_ptr < 8 {
                        state_stack[stack_ptr] = ScanState::InString;
                        stack_ptr += 1;
                    } else {
                        return false;
                    }
                }
            }
        }
    }
    false
}

/// Token types generated by the Byard compiler lexer.
#[derive(Logos, Debug, Clone, Copy, PartialEq, Eq)]
pub enum Token {
    /// The `View` keyword.
    #[token("View")]
    View,

    /// Left parenthesis `(`.
    #[token("(")]
    LParen,
    /// Right parenthesis `)`.
    #[token(")")]
    RParen,
    /// Left brace `{`.
    #[token("{")]
    LBrace,
    /// Right brace `}`.
    #[token("}")]
    RBrace,
    /// Colon `:`.
    #[token(":")]
    Colon,
    /// Comma `,`.
    #[token(",")]
    Comma,

    /// Native style modifier identifier (e.g. `#color`, `#width`).
    #[regex("#[a-zA-Z_][a-zA-Z0-9_]*")]
    StyleIdent,

    /// General identifier.
    #[regex("[a-zA-Z_][a-zA-Z0-9_]*")]
    Ident,

    /// Numeric literal token (e.g., `42`, `3.14`).
    #[regex(r"[0-9]+(?:\.[0-9]+)?")]
    Number,

    /// String literal token containing optional interpolations.
    #[token("\"", scan_interpolated_string)]
    StrLit,

    /// Whitespace characters.
    #[regex(r"[ \t\r\n]+", logos::skip)]
    /// Single line comment.
    #[regex(r"//[^\n]*", logos::skip)]
    Whitespace,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_string() {
        let mut lex = Token::lexer("\"hello\"");
        assert_eq!(lex.next(), Some(Ok(Token::StrLit)));
        assert_eq!(lex.slice(), "\"hello\"");
    }

    #[test]
    fn test_interpolated_string() {
        let mut lex = Token::lexer("\"hello {name}\"");
        assert_eq!(lex.next(), Some(Ok(Token::StrLit)));
        assert_eq!(lex.slice(), "\"hello {name}\"");
    }

    #[test]
    fn test_nested_interpolated_string() {
        let mut lex = Token::lexer("\"hello {f(\\\"world\\\")}\"");
        assert_eq!(lex.next(), Some(Ok(Token::StrLit)));
        assert_eq!(lex.slice(), "\"hello {f(\\\"world\\\")}\"");
    }

    #[test]
    fn test_unescaped_nested_interpolated_string() {
        let mut lex = Token::lexer("\"hello {f(\"world\")}\"");
        assert_eq!(lex.next(), Some(Ok(Token::StrLit)));
        assert_eq!(lex.slice(), "\"hello {f(\"world\")}\"");
    }

    #[test]
    fn test_lexer_tokens() {
        let mut lex = Token::lexer("View MyView(id) { Column(#width: 100, #color: \"red\") }");
        assert_eq!(lex.next(), Some(Ok(Token::View)));
        assert_eq!(lex.next(), Some(Ok(Token::Ident))); // MyView
        assert_eq!(lex.next(), Some(Ok(Token::LParen)));
        assert_eq!(lex.next(), Some(Ok(Token::Ident))); // id
        assert_eq!(lex.next(), Some(Ok(Token::RParen)));
        assert_eq!(lex.next(), Some(Ok(Token::LBrace)));
        assert_eq!(lex.next(), Some(Ok(Token::Ident))); // Column
        assert_eq!(lex.next(), Some(Ok(Token::LParen)));
        assert_eq!(lex.next(), Some(Ok(Token::StyleIdent))); // #width
        assert_eq!(lex.next(), Some(Ok(Token::Colon)));
        assert_eq!(lex.next(), Some(Ok(Token::Number))); // 100
        assert_eq!(lex.next(), Some(Ok(Token::Comma)));
        assert_eq!(lex.next(), Some(Ok(Token::StyleIdent))); // #color
        assert_eq!(lex.next(), Some(Ok(Token::Colon)));
        assert_eq!(lex.next(), Some(Ok(Token::StrLit))); // "red"
        assert_eq!(lex.next(), Some(Ok(Token::RParen)));
        assert_eq!(lex.next(), Some(Ok(Token::RBrace)));
        assert_eq!(lex.next(), None);
    }
}
